[2022-09-05  15:32:43.228] base.py -> post_method line:39 [INFO] : case_id:1 - 登录测试
[2022-09-05  15:32:43.379] base.py -> post_method line:47 [INFO] : 请求体-->{"account": "18988889999", "accountType": 1, "cerificationType": 2}
[2022-09-05  15:32:43.380] base.py -> post_method line:48 [INFO] : 响应体-->{'code': 200, 'success': 1, 'message': '操作成功', 'data': {'smsCode': '5672'}, 'time': 1662363163368, 'traceId': 'dbd268a2-108d-47fa-b6d0-cf61dbe103a3'}
[2022-09-05  15:32:51.132] base.py -> equal line:109 [INFO] : row:1.0--pass
[2022-09-05  15:32:51.132] base.py -> equal line:118 [ERROR] : 操作成功 != None ->断言失败--FAIL
